export type Language = 'hi' | 'cg' | 'en';

export const translations = {
  hi: {
    appName: 'ग्रामीण किराना',
    appSubtitle: 'गाँव की दुकान का 100% ऑफलाइन बिलिंग व बही-खाता',
    online: 'इंटरनेट चालू',
    offline: '100% ऑफलाइन चालू (डाटा सुरक्षित)',
    tabs: {
      pos: '⚡ तुरंत बिलिंग (POS)',
      khata: '📒 बही-खाता (उधार)',
      mandi: '🛒 मंडी खरीदारी लिस्ट',
      spoilage: '⚠️ खराबी व एक्सपायरी',
      inventory: '📦 पूरा स्टॉक लिस्ट',
      settings: '⚙️ सेटिंग्स व बैकअप',
      cashClose: '🏦 गल्ला हिसाब',
      haat: '🎪 हाट मोड',
      more: '☰ मेनू'
    },
    pos: {
      searchPlaceholder: 'सामान खोजें (जैसे: चावल, तेल, कुरकुरे, टॉफी)...',
      allCategories: 'सभी',
      categoryNames: {
        staples: 'अनाज व आटा',
        pulses: 'दालें',
        oils: 'तेल व घी',
        spices: 'मसाले व शक्कर',
        snacks: 'नाश्ता, बिस्कुट व बच्चों का खजाना',
        hygiene: 'साबुन व सफाई',
        dairy: 'दूध व पेय',
        rural_special: 'ग्रामीण स्पेशल'
      },
      cartTitle: 'चालू बिल पर्ची',
      emptyCart: 'बिल में अभी कोई सामान नहीं है। बाईं तरफ से सामान चुनें।',
      looseSelector: 'खुला वजन चुनें:',
      looseGram: 'ग्राम',
      looseKg: 'किलो',
      customItem: 'अन्य सामान जोड़ें (+)',
      customItemName: 'सामान का नाम',
      customItemPrice: 'मूल्य (₹)',
      totalPayable: 'कुल देय राशि:',
      paymentMode: 'भुगतान का प्रकार:',
      cash: 'नकद (Cash)',
      udhaar: 'उधार खाता (Credit)',
      upi: 'ऑनलाइन (UPI)',
      selectCustomer: 'ग्राहक चुनें (खाता जोड़ने के लिए)',
      finishBill: 'बिल पूरा करें (पर्ची बनाएं)',
      billSuccess: 'बिल सफलतापूर्वक दर्ज हो गया!',
      printShare: 'व्हाट्सएप पर पर्ची भेजें',
      clearCart: 'बिल रद्द करें',
      editRate: 'दर बदलें',
      todayRate: 'आज का भाव (दर)',
      saveToCatalog: 'आगे के लिए भी नया भाव सुरक्षित करें',
      ratePerUnit: 'प्रति'
    },
    khata: {
      title: 'ग्राहक उधार (बही-खाता)',
      subtitle: 'गाँव के फसल चक्र व डीबीटी से जुड़ा डिजिटल हिसाब-किताब',
      totalUdhaar: 'गाँव का कुल बाकी (उधार)',
      totalCustomers: 'उधार खाता ग्राहक',
      overdueWarning: 'भुगतान की तारीख पार',
      searchCustomer: 'ग्राहक का नाम या फोन नंबर खोजें...',
      filterByPara: 'पारा / मोहल्ला अनुसार देखें:',
      allParas: 'सभी मोहल्ले/पारे',
      newCustomerBtn: '+ नया ग्राहक जोड़ें',
      jamaBtn: 'जमा (+)',
      udhaarBtn: 'उधार (-)',
      balance: 'बकाया:',
      dueDate: 'भुगतान वादा तारीख:',
      repaymentReason: 'भुगतान का साधन:',
      reasons: {
        KHARIF_DHAN: '🌾 धान खरीदी (समर्थन मूल्य)',
        MONTHLY_DBT: '🏛️ महतारी वंदन / PM-किसान',
        WEEKLY_HAAT: '🎪 साप्ताहिक हाट-बाजार',
        OTHER: 'अन्य'
      },
      whatsappReminder: 'व्हाट्सएप तगादा',
      viewLedger: 'पूरा हिसाब देखें',
      digitalPassbook: '📖 डिजिटल पासबुक',
      noHistory: 'कोई लेन-देन नहीं है'
    },
    mandi: {
      title: 'मंडी / शहर खरीदारी योजना',
      subtitle: 'तहसील मंडी जाने से पहले कम स्टॉक का हिसाब और कुल बजट',
      estimatedBudget: 'मंडी में जरूरी अनुमानित नकद (बजट)',
      itemsToBuy: 'खरीदने योग्य सामान',
      autoGeneratedNotice: 'जिन सामानों का स्टॉक न्यूनतम सीमा से नीचे है, वे यहाँ स्वतः जुड़ गए हैं।',
      productName: 'सामान का नाम',
      currentStock: 'दुकान में बचा स्टॉक',
      suggestedQty: 'मंडी से लाने की मात्रा',
      wholesalePrice: 'अनुमानित थोक दर',
      totalCost: 'कुल लागत',
      shareWholesaler: '📲 शहर के थोक व्यापारी को व्हाट्सएप पर लिस्ट भेजें',
      addItemManually: '+ लिस्ट में और सामान जोड़ें',
      dailyRateSheet: '🌅 दैनिक भाव शीट',
      dailyRateSheetSubtitle: 'सुबह 1-क्लिक में मुख्य सामान के आज के खुदरा भाव अपडेट करें',
      applyAllRates: '💾 सभी नए भाव लागू करें',
      shareRateBoard: '📲 व्हाट्सएप पर आज का रेट बोर्ड भेजें',
      currentRate: 'वर्तमान भाव',
      todayNewRate: 'आज का नया भाव',
      staplesOnly: '🌾 दैनिक मुख्य वस्तुएं',
      allItems: '📦 सभी सामान'
    },
    spoilage: {
      title: 'खराबी व एक्सपायरी सुरक्षा गार्ड',
      subtitle: 'बिजली कटौती, गर्मी या चूहों से होने वाले नुकसान का सटीक हिसाब',
      totalLoss: 'खराबी से कुल नुकसान',
      logLossBtn: '+ नुकसान दर्ज करें',
      expiringSoon: 'अगले 7 दिनों में एक्सपायर होने वाले सामान',
      noExpiring: 'कोई सामान जल्द एक्सपायर नहीं होने वाला है।',
      expiringBannerTitle: 'सामान एक्सपायरी चेतावनी',
      distributorClaimBtn: '📲 डिस्ट्रीब्यूटर वापसी क्लेम (WhatsApp)',
      reasonLabels: {
        POWER_CUT: '⚡ बिजली कटौती / लोड शेडिंग (दूध/दही/कोल्ड ड्रिंक)',
        HEAT_DAMAGE: '☀️ अत्यधिक गर्मी / नमी से खराबी',
        EXPIRED: '⌛ एक्सपायरी डेट खत्म (वापसी नहीं हुई)',
        RODENT_PEST: '🐀 चूहा / कीड़े (घुन) द्वारा नुकसान',
        OTHER: 'अन्य कारण'
      }
    },
    voice: {
      btn: '🎤 बोलकर दर्ज करें (आवाज़)',
      listening: 'सुन रहे हैं... कृपया बोलें (जैसे: "रमेश 200 उधार" या "सरसों तेल")',
      stopListening: 'रोकें',
      recognized: 'पहचाना गया:',
      help: '💡 आप बोल सकते हैं: "चावल 2 किलो", "रमेश 150 उधार", "सुरेश 500 जमा"'
    },
    backup: {
      title: 'डेटा बैकअप व सुरक्षा',
      subtitle: 'फोन खोने या खराब होने पर डेटा सुरक्षित रखने के लिए बैकअप फ़ाइल डाउनलोड करें',
      exportBtn: '📥 पूरा बैकअप डाउनलोड करें (JSON फ़ाइल)',
      importBtn: '📤 बैकअप फ़ाइल से डेटा पुनर्स्थापित करें',
      clearNotice: 'यह ऐप आपके फोन के अंदर बिना इंटरनेट 100% सुरक्षित रूप से चलता है।',
      archiveTitle: 'वित्तीय वर्ष डेटा आर्काइव व स्थानीय स्टोरेज सफाई',
      archiveSubtitle: 'पुराने बिलों को सुरक्षित कोल्ड स्टोरेज में सहेजें ताकि ऐप हमेशा सुपरफ़ास्ट चले',
      activeSales: 'सक्रिय बिल (POS)',
      archivedSales: 'आर्काइव बिल',
      archivedTxns: 'आर्काइव खाता',
      estimatedStorage: 'अनुमानित डिवाइस स्टोरेज',
      archiveBtn: '📦 180 दिन से पुराने बिल आर्काइव करें',
      exportArchiveBtn: '📥 बिल आर्काइव डाउनलोड करें',
      archiveKhataBtn: '📒 निपट चुके पुराने खाते आर्काइव करें',
      exportKhataArchiveBtn: '📥 खाता आर्काइव डाउनलोड करें'
    },
    cloudSync: {
      syncNow: 'क्लाउड सिंक करें',
      synced: 'क्लाउड सुरक्षित',
      pending: 'सिंक बाकी',
      ownerRole: 'दुकानदार (Owner)',
      cashierRole: 'काउंटर मुनीम (Cashier)'
    },
    cashClose: {
      title: 'दैनिक गल्ला व रोकड़ हिसाब',
      subtitle: 'शाम का गल्ला बंद करें — नकद मिलान, खर्च और व्हाट्सएप दिन सारांश',
      physicalCash: 'गल्ले में गिना हुआ नकद (₹)',
      physicalCashHint: 'दराज / गल्ले में वास्तविक नोट-सिक्के गिनें',
      openingCashLabel: 'शुरुआती रोकड़ / सुबह का गल्ला (Float)',
      openingCashHint: 'सुबह गल्ले में रखा हुआ खुल्ला पैसा',
      denominationCounter: '💵 नोट व सिक्के गिनें',
      denominationClose: 'कैलकुलेटर छुपाएं',
      denominationApply: 'कुल राशि गल्ले में भरें',
      totalUpiSalesLabel: '📲 UPI / ऑनलाइन बिक्री',
      totalGrossSalesLabel: 'कुल दिन का कारोबार',
      reopenDayBtn: '🔓 गल्ला पुनः खोलें / संशोधित करें',
      reopenConfirm: 'क्या आप आज के गल्ला रिकॉर्ड को पुनः खोलकर सुधारना चाहते हैं?',
      cashSalesLabel: 'आज का नकद बिक्री (Cash Sales)',
      jamaLabel: 'आज जमा मिला उधार (Jama Collected)',
      expensesLabel: 'आज के खर्चे (Tempo, मजदूरी, चाय आदि)',
      addExpense: '+ खर्च जोड़ें',
      expenseDesc: 'खर्च का विवरण',
      expenseAmt: 'राशि (₹)',
      expectedCash: 'अपेक्षित कुल नकद',
      difference: 'गल्ला मिलान (अंतर)',
      excess: 'अतिरिक्त नकद (बचत)',
      shortage: 'नकद कम है (घाटा)',
      matched: 'गल्ला बिल्कुल मिला! ✅',
      note: 'नोट / टिप्पणी (वैकल्पिक)',
      closeDayBtn: 'दिन बंद करें व सुरक्षित करें',
      whatsappSummary: '📲 व्हाट्सएप पर दिन सारांश भेजें',
      printSummary: '🖨️ थर्मल प्रिंटर से पर्ची',
      closedAt: 'गल्ला बंद समय:',
      noHistory: 'आज कोई गल्ला बंद नहीं हुआ है',
      todayDate: 'आज की तारीख',
      bluetoothConnect: 'ब्लूटूथ प्रिंटर से जोड़ें',
      printFallback: 'ब्राउज़र प्रिंट (58mm)',
      eveningReminder: 'शाम का गल्ला मिलान बाकी है',
      closePendingBadge: 'मिलान बाकी'
    },
    haatMode: {
      title: 'साप्ताहिक हाट-बाजार मोड',
      subtitle: 'हाट की भारी भीड़ में 2 सेकंड में नकद बिक्री — मोटी बटन, 1-टैप नकद',
      todayCash: 'आज हाट कुल नकद',
      todayBills: 'कुल ग्राहक',
      quickTender: 'नकद प्राप्त (Tender):',
      changeReturn: 'वापस देने योग्य खुल्ले (Change):',
      finishBill: '⚡ 1-टैप नकद पूरा (₹',
      finishBillUpi: '⚡ 1-टैप UPI पूरा (₹',
      billSuccess: 'बिक्री पूरी हुई! अगला ग्राहक तैयार ➔',
      autoPrint: 'प्रिंटर पर्ची (58mm)',
      clearCart: 'रद्द करें',
      adHocItem: '⚡ खुला सामान / भाजी (+₹)',
      paymentMode: 'भुगतान तरीका:',
      cashMode: '💵 नकद (Cash)',
      upiMode: '📲 UPI (QR कोड)',
      lowStockBadge: '⚠️ कम स्टॉक',
      soundOn: '🔊 आवाज़ चालू',
      soundOff: '🔇 आवाज़ बंद'
    },
    subscription: {
      modalTitle: 'ग्रामीण किराना — सुविधाएं व प्लान',
      modalSubtitle: 'गाँव की हर छोटी-बड़ी दुकान के लिए पारदर्शी व मुफ़्त समाधान',
      freePlanTitle: '🌾 गाँव स्टार्टर (मुफ़्त)',
      freePlanPrice: '₹0',
      freePlanPeriod: 'आजीवन मुफ़्त',
      freePlanDesc: 'गाँव की एकल दुकान के लिए सम्पूर्ण ऑफ़लाइन समाधान। कभी कोई चार्ज नहीं।',
      proPlanTitle: '🚀 ग्रामिन प्रो (क्लाउड व स्टाफ)',
      proPlanPrice: '₹99',
      proPlanPeriod: 'प्रति माह (या ₹999/वर्ष)',
      proPlanDesc: 'WhatsApp तगादा ब्लास्ट, माहवारी P&L रिपोर्ट, कम स्टॉक अलर्ट, मुनीम PIN व क्लाउड बैकअप।',
      activeBadge: 'वर्तमान सक्रिय प्लान',
      upgradeBtn: 'प्रो में अपग्रेड करें (WhatsApp)',
      startFreeBtn: '+ अपनी दुकान मुफ़्त में जोड़ें',
      allFeaturesTitle: '🎯 ग्रामीण किराना की प्रमुख खूबियाँ',
      features: {
        offline: '100% ऑफ़लाइन चालू — बिना इंटरनेट या बिजली के कभी बिलिंग नहीं रुकती',
        pos: 'तुरंत बिलिंग व बारकोड स्कैनर — फोन कैमरा व 1-टैप पाव/आधा किलो वजन',
        khata: 'डिजिटल बही-खाता — फसल चक्र व महतारी वंदन अनुसार उधारी व 1-टैप व्हाट्सएप तकादा',
        haat: 'साप्ताहिक हाट मोड — बाज़ार की भीड़ में 2 सेकंड में 1-टैप नकद हिसाब',
        thermal: 'ब्लूटूथ थर्मल प्रिंटर — 58mm सस्ती पर्ची व ग्राहक खाता विवरण प्रिंट',
        galla: 'दैनिक गल्ला हिसाब — शाम को नकद मिलान, दुकान खर्चे व व्हाट्सएप दिन सारांश',
        cloud: 'क्लाउड बैकअप (प्रो) — फोन टूटने/गुमने पर भी पाई-पाई का हिसाब सुरक्षित',
        staff: 'मुनीम/स्टाफ खाता (प्रो) — थोक खरीद भाव व मुनाफ़ा छुपाकर सुरक्षित बिलिंग',
        whatsappBlast: '📲 WhatsApp तगादा ब्लास्ट (प्रो) — सभी उधारी ग्राहकों को 1-टैप में याद दिलाएं',
        plReport: '📊 माहवारी लाभ-हानि रिपोर्ट (प्रो) — बिक्री, लागत, खराबी व शुद्ध मुनाफ़ा PDF',
        lowStock: '🔔 कम स्टॉक सुबह अलर्ट (प्रो) — न्यूनतम सीमा से कम सभी सामान की सूचना',
        munimPin: '👥 मुनीम/स्टाफ PIN लॉगिन (प्रो) — काउंटर स्टाफ से रिपोर्ट व सेटिंग्स छुपाएं'
      },
      currentPlanLabel: 'आपकी दुकान का प्लान:',
      currentPlanFree: '🌾 गाँव स्टार्टर (मुफ़्त)',
      currentPlanPro: '👑 ग्रामिन प्रो'
    },
    learnBtn: '❓ सीखें',
    tour: {
      modalTitle: 'ग्रामीण किराना — 1 मिनट में सीखें',
      modalSubtitle: 'दुकानदार व मुनीम के लिए सरल सचित्र गाइड',
      slides: [
        {
          title: '1. तुरंत बिलिंग (1-टैप POS)',
          icon: '🧾',
          desc: 'सामान के नाम या फोटो पर सिर्फ 1 बार छूएं, वह तुरंत चालू बिल में जुड़ जाएगा। नकद, उधार या UPI QR चुनें और 1-सेकंड में ग्राहक को बिल पर्ची दें या व्हाट्सएप पर भेजें।',
          badge: 'तेज़ व आसान'
        },
        {
          title: '2. ग्राहक उधारी (बही-खाता)',
          icon: '👥',
          desc: 'गाँव के पारा या मोहल्ला अनुसार ग्राहक चुनें। धान कटाई या महतारी वंदन की वादा तारीख लिखें। उधारी सीमा पार होने पर लाल चेतावनी दिखेगी और 1 क्लिक में व्हाट्सएप तगादा भेजें।',
          badge: 'उधारी सुरक्षा'
        },
        {
          title: '3. खुला सामान व भाव बदलाव',
          icon: '⚖️',
          desc: 'पाव (250g), आधा किलो (500g) या ₹10-₹20 के खुले सिक्के भाव सीधे बेचें। रोज़ सुबह नया मंडी भाव केवल 1 टैप में बदल सकते हैं।',
          badge: 'पाव व आधा किलो'
        },
        {
          title: '4. शाम का गल्ला हिसाब (कैश क्लोज)',
          icon: '🔒',
          desc: 'दुकान बढ़ाने के समय 500, 200, 100, 50, 20, 10 के नोट गिनकर गल्ले में दर्ज करें। दिन भर की कुल नकद बिक्री का मिलान करें और व्हाट्सएप पर दिन का हिसाब भेजें।',
          badge: 'रोकड़ सुरक्षा'
        }
      ],
      startPracticeBtn: '🚀 1 मिनट का अभ्यास बिल बनाकर देखें',
      skipBtn: '✕ बाद में सीखें',
      prevBtn: 'पिछला',
      nextBtn: 'अगला',
      practiceBar: {
        step1: '👆 स्टेप 1: नीचे किसी भी सामान (जैसे शक्कर या तेल) पर टैप करें',
        step2: '👆 स्टेप 2: नकद/उधार चुनें और नीचे "बिल पूरा करें" पर टैप करें',
        exitTour: '✕ अभ्यास बंद करें'
      },
      celebration: {
        title: '🎉 शाबाश! आपका पहला बिल तैयार है!',
        subtitle: 'आपने सफलतापूर्वक ग्रामीण किराना पर बिलिंग करना सीख लिया है।',
        note: '💡 ध्यान दें: यह सिर्फ आपका सीखने का अभ्यास बिल था। असली दुकान के बही-खाते और स्टॉक में कोई बदलाव नहीं हुआ है।',
        startRealBtn: '✅ अब असली बिलिंग शुरू करें',
        retryBtn: '🔄 दोबारा अभ्यास करें'
      },
      welcomePrompt: {
        title: 'नमस्ते! क्या आप 1 मिनट में पहला बिल बनाना सीखना चाहते हैं?',
        startBtn: '🚀 हाँ, अभ्यास बिल सीखें',
        dismissBtn: 'बाद में'
      }
    },
    share: {
      title: 'साथी दुकानदार को शेयर करें',
      subtitle: 'गाँव के अन्य व्यापारी भाइयों को डिजिटल किराना से जोड़ें',
      whatsappBtn: 'WhatsApp पर शेयर करें',
      instagramBtn: 'Instagram Bio / DM लिंक',
      shareSheetBtn: 'अन्य ऐप पर भेजें',
      copyBtn: 'लिंक कॉपी करें',
      copied: 'लिंक कॉपी हो गया! ✅',
      referralNotice: '🎁 रेफरल बोनस: साथी को जोड़ने पर आप दोनों को +15 दिन प्रो ट्रायल मुफ़्त!',
      messageTemplate: 'नमस्ते! मैं अपनी दुकान पर "ग्रामीण किराना" ऐप का उपयोग कर रहा हूँ। यह 100% बिना इंटरनेट चलता है — तुरंत बिलिंग, उधारी बही-खाता, बारकोड स्कैनर और ब्लूटूथ प्रिंटर सब कुछ मुफ़्त है। आप भी अपनी दुकान के लिए आज़माएं:\n\n'
    },
    faqs: {
      title: 'अक्सर पूछे जाने वाले सवाल (FAQs)',
      subtitle: 'गाँव के दुकानदारों द्वारा सबसे ज़्यादा पूछे जाने वाले सवालों के सीधे जवाब',
      badge: 'मदद व समाधान',
      startShopAction: '👉 अभी अपनी दुकान शुरू करें (15 सेकंड में) ➔',
      items: [
        {
          q: 'क्या यह ऐप सच में बिना इंटरनेट (100% ऑफ़लाइन) काम करता है?',
          a: 'जी हाँ! ग्रामीण किराना को विशेष रूप से गाँव के कमजोर नेटवर्क व बिजली कटौती को ध्यान में रखकर बनाया गया है। बिलिंग, उधारी बही-खाता, बारकोड स्कैनिंग, हाट मोड और गल्ला हिसाब बिना इंटरनेट के बिल्कुल सुपरफ़ास्ट चलते हैं। नेटवर्क आने पर डेटा स्वतः सुरक्षित रूप से सिंक हो जाता है।'
        },
        {
          q: 'क्या "गाँव स्टार्टर" प्लान सच में हमेशा मुफ़्त (Free Forever) है?',
          a: 'बिल्कुल! गाँव स्टार्टर प्लान ₹0 आजीवन मुफ़्त है। इसमें ऑफ़लाइन बिलिंग, असीमित उधारी खाता, बारकोड स्कैनर, साप्ताहिक हाट मोड और 58mm ब्लूटूथ प्रिंटिंग के लिए कभी कोई चार्ज नहीं लिया जाता।'
        },
        {
          q: 'यदि मेरा फोन खराब, चोरी या गुम हो जाए, तो क्या दुकान का डेटा सुरक्षित रहेगा?',
          a: 'हाँ, 100% सुरक्षित! ऐप में "डेटा बैकअप" (JSON फ़ाइल) डाउनलोड करने की सुविधा है। इसके अलावा प्रो प्लान में सुरक्षित क्लाउड ऑटो-बैकअप मिलता है, जिससे नए फोन में सिर्फ अपना मोबाइल नंबर व गुप्त पिन डालते ही पूरी दुकान, सभी ग्राहकों की उधारी और स्टॉक 1 सेकंड में वापस आ जाता है।'
        },
        {
          q: 'क्या मुझे कोई महंगा कंप्यूटर, बारकोड गन या प्रिंटर खरीदना पड़ेगा?',
          a: 'बिल्कुल नहीं! आप अपने किसी भी साधारण 4G एंड्रॉयड स्मार्टफोन से पूरा काम कर सकते हैं। बारकोड स्कैनिंग सीधे फोन के कैमरे से होती है। यदि आप ग्राहकों को पक्की पर्ची देना चाहते हैं, तो मात्र ₹1200-₹1500 का कोई भी सस्ता पॉकेट ब्लूटूथ थर्मल प्रिंटर जोड़ सकते हैं।'
        },
        {
          q: 'क्या ग्राहकों को उनके WhatsApp पर उधारी और बिल की रसीद मिलेगी?',
          a: 'हाँ! हर बिल कटने पर, उधारी सामान ले जाने पर या जमा मिलने पर आप केवल 1 टैप में ग्राहक के WhatsApp पर सुंदर रसीद भेज सकते हैं। साथ ही ग्राहक को एक सुरक्षित डिजिटल पासबुक लिंक मिलता है, जिससे वह अपने फोन पर पूरा पुराना हिसाब देख सकता है।'
        },
        {
          q: 'दुकान पर मुनीम या लड़का बैठता है — क्या वह मेरा मुनाफ़ा और थोक खरीद भाव देख पाएगा?',
          a: 'बिल्कुल नहीं! आप मुनीम के लिए अलग 4-अंकों का गुप्त PIN सेट कर सकते हैं। मुनीम केवल ग्राहक का बिल काट सकता है। दुकान का शुद्ध मुनाफ़ा, थोक खरीद भाव, गल्ला हिसाब, मंडी डायरी और सेटिंग्स मुनीम से पूरी तरह सुरक्षित और छिपे रहते हैं।'
        },
        {
          q: 'ऐप में अपनी दुकान शुरू करने में कितना समय लगता है?',
          a: 'सिर्फ 15 से 30 सेकंड! अपना मोबाइल नंबर और 4-अंकों का गुप्त पिन बनाएं। दुकान सेटअप विज़ार्ड की मदद से गाँव में बिकने वाले 52 प्रसिद्ध किराना सामान (शक्कर, तेल, दाल, बिस्कुट, साबुन आदि) केवल 1 क्लिक में लोड हो जाते हैं।'
        }
      ]
    }
  },
  cg: {
    appName: 'ग्रामीण किराना',
    appSubtitle: 'गाँव के दुकान बर बिना इंटरनेट के डिजिटल बही-खाता अउ बिलिंग',
    online: 'नेटवर्क चालू हे',
    offline: '100% बिना नेट के चालू (डाटा सुरक्षित हे)',
    tabs: {
      pos: '⚡ तुरंत बिलिंग (POS)',
      khata: '📒 बही-खाता (उधार-बाकी)',
      mandi: '🛒 मंडी खरीदारी लिस्ट',
      spoilage: '⚠️ खराबी अउ नुकसान',
      inventory: '📦 सबो सामान के स्टॉक',
      settings: '⚙️ सेटिंग्स अउ बैकअप',
      cashClose: '🏦 गल्ला हिसाब',
      haat: '🎪 हाट-बाजार',
      more: '☰ मेनू'
    },
    pos: {
      searchPlaceholder: 'सामान खोजव (जैसे: चांउर, तेल, कुरकुरे, टॉफी)...',
      allCategories: 'सबो',
      categoryNames: {
        staples: 'अनाज अउ आटा',
        pulses: 'दाल मन',
        oils: 'तेल अउ घीव',
        spices: 'मसाला अउ शक्कर',
        snacks: 'नाश्ता, बिस्कुट अउ लइका मन के खजाना',
        hygiene: 'साबुन अउ सफाई',
        dairy: 'दूध अउ पेय',
        rural_special: 'गाँव-देहात स्पेशल'
      },
      cartTitle: 'चालू बिल पर्ची',
      emptyCart: 'बिल म अभी कोनो सामान नइये। बांया डहर ले सामान चुनव।',
      looseSelector: 'खुला तौल चुनव:',
      looseGram: 'ग्राम',
      looseKg: 'किलो',
      customItem: 'अउ सामान जोड़व (+)',
      customItemName: 'सामान के नाव',
      customItemPrice: 'दाम (₹)',
      totalPayable: 'जम्मा देय रकम:',
      paymentMode: 'रुपिया देय के तरीका:',
      cash: 'नगद (Cash)',
      udhaar: 'उधार बाकी (Credit)',
      upi: 'ऑनलाइन (UPI)',
      selectCustomer: 'ग्राहक चुनव (खाता म जोड़े बर)',
      finishBill: 'बिल पूरा करव (पर्ची बनाव)',
      billSuccess: 'बिल बढ़िया से दर्ज हो गे!',
      printShare: 'व्हाट्सएप म पर्ची भेजव',
      clearCart: 'बिल रद्द करव',
      editRate: 'भाव बदलव',
      todayRate: 'आज के भाव',
      saveToCatalog: 'आगे बर घलोक नवा भाव रखव',
      ratePerUnit: 'प्रति'
    },
    khata: {
      title: 'ग्राहक के उधार (बही-खाता)',
      subtitle: 'गाँव के धान फसल अउ महतारी वंदन ले जुड़े डिजिटल हिसाब',
      totalUdhaar: 'गाँव के जम्मा बाकी (उधार)',
      totalCustomers: 'उधार खाता ग्राहक मन',
      overdueWarning: 'भुगतान के वादा तारीख पार',
      searchCustomer: 'ग्राहक के नाव या फोन नंबर खोजव...',
      filterByPara: 'पारा / मोहल्ला अनुसार देखव:',
      allParas: 'सबो पारा / मोहल्ला',
      newCustomerBtn: '+ नवा ग्राहक जोड़व',
      jamaBtn: 'जमा (+)',
      udhaarBtn: 'उधार (-)',
      balance: 'बाकी रकम:',
      dueDate: 'पैसा देय के वादा तारीख:',
      repaymentReason: 'पैसा देय के साधन:',
      reasons: {
        KHARIF_DHAN: '🌾 धान खरीदी (समर्थन मूल्य म)',
        MONTHLY_DBT: '🏛️ महतारी वंदन / PM-किसान',
        WEEKLY_HAAT: '🎪 अठवरिया हाट-बाजार',
        OTHER: 'दूसर'
      },
      whatsappReminder: 'व्हाट्सएप तगादा',
      viewLedger: 'सब्बो हिसाब देखव',
      digitalPassbook: '📖 डिजिटल पासबुक',
      noHistory: 'कोनो लेन-देन नइये'
    },
    mandi: {
      title: 'मंडी / सहर ले खरीदारी योजना',
      subtitle: 'तहसील मंडी जाय के पहिली कम स्टॉक के हिसाब अउ कुल खर्चा',
      estimatedBudget: 'मंडी बर जरूरी अनुमानित नगद रकम',
      itemsToBuy: 'लाए बर सामान मन',
      autoGeneratedNotice: 'जोन सामान के स्टॉक कम हो गे हे, वो मन अपने-आप जुड़ गे हे।',
      productName: 'सामान के नाव',
      currentStock: 'दुकान म बांचे स्टॉक',
      suggestedQty: 'मंडी ले लाए के मात्रा',
      wholesalePrice: 'थोक भाव (दर)',
      totalCost: 'जम्मा लागत',
      shareWholesaler: '📲 सहर के थोक व्यापारी ला व्हाट्सएप म लिस्ट भेजव',
      addItemManually: '+ लिस्ट म अउ सामान जोड़व',
      dailyRateSheet: '🌅 दैनिक भाव शीट',
      dailyRateSheetSubtitle: 'बिहनिया 1-क्लिक म मुख्य सामान के आज के खुदरा भाव बदलव',
      applyAllRates: '💾 सबो नवा भाव लागू करव',
      shareRateBoard: '📲 व्हाट्सएप म आज के रेट बोर्ड भेजव',
      currentRate: 'अब्बड़ के भाव',
      todayNewRate: 'आज के नवा भाव',
      staplesOnly: '🌾 दैनिक मुख्य सामान मन',
      allItems: '📦 सबो सामान'
    },
    spoilage: {
      title: 'खराबी अउ एक्सपायरी सुरक्षा गार्ड',
      subtitle: 'करंट कटे ले, घाम या मूसा (चूहा) ले होय नुकसान के हिसाब',
      totalLoss: 'खराबी ले जम्मा नुकसान',
      logLossBtn: '+ नुकसान दर्ज करव',
      expiringSoon: 'आगू 7 दिन म एक्सपायर होवइया सामान',
      noExpiring: 'कोनो सामान अभी एक्सपायर नइ होवत हे।',
      expiringBannerTitle: 'सामान एक्सपायरी चेतावनी',
      distributorClaimBtn: '📲 डिस्ट्रीब्यूटर वापसी क्लेम (WhatsApp)',
      reasonLabels: {
        POWER_CUT: '⚡ करंट कटे ले / लोड शेडिंग (दूध/दही/कोल्ड ड्रिंक खराब)',
        HEAT_DAMAGE: '☀️ घाम (गर्मी) अउ सीलन ले खराबी',
        EXPIRED: '⌛ एक्सपायरी खत्म (थोक व्यापारी नइ बदलीस)',
        RODENT_PEST: '🐀 मूसा (चूहा) या घुन/कीड़ा ले नुकसान',
        OTHER: 'दूसर कारण'
      }
    },
    voice: {
      btn: '🎤 बोल के दर्ज करव',
      listening: 'सुनत हन... बोलव (जैसे: "रमेश 200 उधार" या "सरसों तेल")',
      stopListening: 'रोकव',
      recognized: 'समझेन:',
      help: '💡 बोल सकथो: "चांउर 2 किलो", "रमेश 150 उधार", "सुरेश 500 जमा"'
    },
    backup: {
      title: 'डेटा बैकअप अउ सुरक्षा',
      subtitle: 'मोबाइल बदले या बिगड़े म डेटा सुरक्षित रखे बर बैकअप फ़ाइल डाउनलोड करव',
      exportBtn: '📥 जम्मा बैकअप डाउनलोड करव (फ़ाइल)',
      importBtn: '📤 बैकअप फ़ाइल ले डेटा वापस लावव',
      clearNotice: 'ये ऐप तोर मोबाइल के भीतर बिना नेट के 100% सुरक्षित चलथे।',
      archiveTitle: 'वित्तीय बछर डेटा आर्काइव अउ मोबाइल स्टोरेज सफाई',
      archiveSubtitle: 'पुरना बिल मन ला सुरक्षित कोल्ड स्टोरेज म सहेजव जेकर ले ऐप सुपरफ़ास्ट चले',
      activeSales: 'चालू बिल (POS)',
      archivedSales: 'आर्काइव बिल',
      archivedTxns: 'आर्काइव खाता',
      estimatedStorage: 'मोबाइल स्टोरेज नाप',
      archiveBtn: '📦 180 दिन ले पुरना बिल आर्काइव करव',
      exportArchiveBtn: '📥 बिल आर्काइव डाउनलोड करव',
      archiveKhataBtn: '📒 निपट गे पुरना खाता ला आर्काइव करव',
      exportKhataArchiveBtn: '📥 खाता आर्काइव डाउनलोड करव'
    },
    cloudSync: {
      syncNow: 'क्लाउड सिंक करव',
      synced: 'क्लाउड सुरक्षित हे',
      pending: 'सिंक बाकी हे',
      ownerRole: 'दुकानदार (मालिक)',
      cashierRole: 'काउंटर मुनीम'
    },
    cashClose: {
      title: 'रोजाना गल्ला अउ रोकड़ हिसाब',
      subtitle: 'सांझ के गल्ला बंद करव — नगद मिलान, खर्चा अउ व्हाट्सएप दिन-सारांश',
      physicalCash: 'गल्ला म गिने रोकड़ (₹)',
      physicalCashHint: 'दराज / गल्ला म रखे नोट-सिक्का गिनव',
      openingCashLabel: 'शुरुआती रोकड़ / सुबह के गल्ला',
      openingCashHint: 'सुबह गल्ला म रखे खुल्ला पईसा',
      denominationCounter: '💵 नोट अउ सिक्का गिनव',
      denominationClose: 'कैलकुलेटर लुकावव',
      denominationApply: 'सबो रकम गल्ला म भरव',
      totalUpiSalesLabel: '📲 UPI / ऑनलाइन बिक्री',
      totalGrossSalesLabel: 'कुल दिन के कारोबार',
      reopenDayBtn: '🔓 गल्ला फिर से खोलव / सुधारव',
      reopenConfirm: 'का आप आज के गल्ला हिसाब ला फिर से खोल के सुधारना चाहत हव?',
      cashSalesLabel: 'आज के नगद बिक्री (Cash Sales)',
      jamaLabel: 'आज जमा मिले उधार (जमा)',
      expensesLabel: 'आज के खर्चा (टेम्पो, मजूरी, चाय आदि)',
      addExpense: '+ खर्चा जोड़व',
      expenseDesc: 'खर्चा के बात',
      expenseAmt: 'रकम (₹)',
      expectedCash: 'होना जरूरी रोकड़',
      difference: 'गल्ला मिलान (फरक)',
      excess: 'रोकड़ जादा (बचत)',
      shortage: 'रोकड़ कम हे (घाटा)',
      matched: 'गल्ला एकदम मिल गे! ✅',
      note: 'टिप्पणी (जरूरी नइये)',
      closeDayBtn: 'दिन बंद करव अउ सुरक्षित करव',
      whatsappSummary: '📲 व्हाट्सएप म दिन-सारांश भेजव',
      printSummary: '🖨️ थर्मल प्रिंटर ले पर्ची',
      closedAt: 'गल्ला बंद के समय:',
      noHistory: 'आज कोनो गल्ला बंद नइ होए हे',
      todayDate: 'आज के तारीख',
      bluetoothConnect: 'ब्लूटूथ प्रिंटर जोड़व',
      printFallback: 'ब्राउज़र प्रिंट (58mm)',
      eveningReminder: 'सांझ के गल्ला मिलान बांचे हे',
      closePendingBadge: 'मिलान बांचे'
    },
    haatMode: {
      title: 'साप्ताहिक अठवरिया हाट-बाजार मोड',
      subtitle: 'हाट के भारी भीड़ म 2 सेकंड म नगद बिक्री — मोटी बटन, 1-टैप नगद',
      todayCash: 'आज हाट जम्मा नगद',
      todayBills: 'जम्मा ग्राहक',
      quickTender: 'नगद मिले (रुपिया):',
      changeReturn: 'वापस देय के खुल्ला (Change):',
      finishBill: '⚡ 1-टैप नगद पूरा (₹',
      finishBillUpi: '⚡ 1-टैप UPI पूरा (₹',
      billSuccess: 'बिक्री पूरा हो गे! अगला ग्राहक लावव ➔',
      autoPrint: 'प्रिंटर पर्ची (58mm)',
      clearCart: 'रद्द करव',
      adHocItem: '⚡ खुल्ला सामान / भाजी (+₹)',
      paymentMode: 'पईसा देय के तरीका:',
      cashMode: '💵 नगद (Cash)',
      upiMode: '📲 UPI (QR कोड)',
      lowStockBadge: '⚠️ कम माल',
      soundOn: '🔊 आवाज़ चालू',
      soundOff: '🔇 आवाज़ बंद'
    },
    subscription: {
      modalTitle: 'ग्रामीण किराना — सुविधा अउ प्लान',
      modalSubtitle: 'गाँव के सबो दुकान बर सीधा-सादा अउ मुफ़्त समाधान',
      freePlanTitle: '🌾 गाँव स्टार्टर (मुफ़्त)',
      freePlanPrice: '₹0',
      freePlanPeriod: 'जिंदगी भर मुफ़्त',
      freePlanDesc: 'गाँव के एक दुकान बर पूरा बिना नेट के समाधान। कोनो पईसा नइ लगे।',
      proPlanTitle: '🚀 ग्रामिन प्रो (क्लाउड अउ स्टाफ)',
      proPlanPrice: '₹99',
      proPlanPeriod: 'महीना भर (या ₹999/बछर)',
      proPlanDesc: 'WhatsApp तगादा ब्लास्ट, महीना P&L रिपोर्ट, कम स्टॉक अलर्ट, मुनीम PIN अउ क्लाउड बैकअप।',
      activeBadge: 'अभी चालू प्लान',
      upgradeBtn: 'प्रो म अपग्रेड करव (WhatsApp)',
      startFreeBtn: '+ अपन दुकान मुफ़्त म जोड़व',
      allFeaturesTitle: '🎯 ग्रामीण किराना के सबो सुविधा',
      features: {
        offline: '100% बिना नेट के — बिना नेटवर्क या बिजली के कभू बिलिंग नइ रुके',
        pos: 'तुरंत बिलिंग अउ बारकोड स्कैनर — कैमरा ले स्कैन अउ 1-टैप पाव/आधा किलो',
        khata: 'डिजिटल बही-खाता — धान खरीदी अउ महतारी वंदन अनुसार उधारी अउ व्हाट्सएप तकादा',
        haat: 'साप्ताहिक अठवरिया हाट — मेला-बाजार म 2 सेकंड म 1-टैप नगद हिसाब',
        thermal: 'ब्लूटूथ प्रिंटर — 58mm सस्ता पर्ची अउ ग्राहक खाता प्रिंट',
        galla: 'दैनिक गल्ला हिसाब — संझा के रोकड़ मिलान, खर्चा अउ व्हाट्सएप सारांश',
        cloud: 'क्लाउड बैकअप (प्रो) — मोबाइल फूटे या घुमाए म भी एक-एक पईसा सुरक्षित',
        staff: 'मुनीम खाता (प्रो) — थोक खरीद अउ नफ़ा छुपा के सुरक्षित बिलिंग',
        whatsappBlast: '📲 WhatsApp तगादा ब्लास्ट (प्रो) — सबो उधारी ग्राहक ला 1-टैप म याद दिलावव',
        plReport: '📊 महीना लाभ-हानि रिपोर्ट (प्रो) — बिक्री, लागत, खराबी अउ शुद्ध नफ़ा PDF',
        lowStock: '🔔 कम स्टॉक सुबह अलर्ट (प्रो) — कम माल के सूची के सुबह सूचना',
        munimPin: '👥 मुनीम PIN लॉगिन (प्रो) — काउंटर स्टाफ ले रिपोर्ट अउ सेटिंग छुपावव'
      },
      currentPlanLabel: 'दुकान के प्लान:',
      currentPlanFree: '🌾 गाँव स्टार्टर (मुफ़्त)',
      currentPlanPro: '👑 ग्रामिन प्रो'
    },
    learnBtn: '❓ सीखव',
    tour: {
      modalTitle: 'ग्रामीण किराना — 1 मिनट म सीखव',
      modalSubtitle: 'दुकानदार अउ मुनीम बर सरल सचित्र गाइड',
      slides: [
        {
          title: '1. तुरंत बिलिंग (1-टैप POS)',
          icon: '🧾',
          desc: 'सामान के नाव या फोटो म सिरिफ 1 पइत छूवव, उहू ह तुरंत चालू बिल म जुड़ जाही। नकद, उधार या UPI QR चुनव अउ 1-सेकंड म गाहक ला बिल रसीद देवव या व्हाट्सएप म भेजव।',
          badge: 'तेज़ अउ आसान'
        },
        {
          title: '2. गाहक उधारी (बही-खाता)',
          icon: '👥',
          desc: 'गाँव के पारा या मोहल्ला अनुसार गाहक चुनव। धान लुवाई या महतारी वंदन के वादा तारीख लिखव। उधारी जादा होए म लाल चेतावनी दिखही अउ 1 क्लिक म व्हाट्सएप तगादा भेजव।',
          badge: 'उधारी सुरक्षा'
        },
        {
          title: '3. खुला सामान अउ भाव बदलाव',
          icon: '⚖️',
          desc: 'पाव (250g), आधा किलो (500g) या ₹10-₹20 के खुला सामान सोझे बेचव। रोज बिहनिया नवा मंडी भाव सिरिफ 1 टैप म बदल सकथो।',
          badge: 'पाव अउ आधा किलो'
        },
        {
          title: '4. संझा के गल्ला हिसाब (कैश क्लोज)',
          icon: '🔒',
          desc: 'दुकान बढ़ाए के बेरा 500, 200, 100, 50, 20, 10 के नोट गिन के गल्ला म दर्ज करव। दिन भर के नकद बिक्री के मिलान करव अउ व्हाट्सएप म संझा के हिसाब भेजव।',
          badge: 'रोकड़ सुरक्षा'
        }
      ],
      startPracticeBtn: '🚀 1 मिनट के अभ्यास बिल बना के देखव',
      skipBtn: '✕ पाछू सीखहूं',
      prevBtn: 'पाछू',
      nextBtn: 'आगू',
      practiceBar: {
        step1: '👆 स्टेप 1: नीचे कोनो भी सामान (जैसे शक्कर या तेल) म टैप करव',
        step2: '👆 स्टेप 2: नकद/उधार चुनव अउ नीचे "बिल पूरा करव" म टैप करव',
        exitTour: '✕ अभ्यास बंद करव'
      },
      celebration: {
        title: '🎉 शाबाश! तोर पहिली बिल तैयार हे!',
        subtitle: 'तँय सफलतापूर्वक ग्रामीण किराना म बिलिंग करना सीख गए हवव।',
        note: '💡 सुरता राखव: ये सिरिफ सीखे बर अभ्यास बिल रहिस। असली दुकान के बही-खाता म कोनो बदलाव नइ होए हे।',
        startRealBtn: '✅ अब असली बिलिंग शुरू करव',
        retryBtn: '🔄 फेर ले अभ्यास करव'
      },
      welcomePrompt: {
        title: 'नमस्ते! का तँय 1 मिनट म पहिली बिल बनाना सीखना चाहत हव?',
        startBtn: '🚀 हव, अभ्यास बिल सीखव',
        dismissBtn: 'पाछू'
      }
    },
    share: {
      title: 'संगी व्यापारी ला शेयर करव',
      subtitle: 'गाँव के दूसर दुकानदार संगी मन ला डिजिटल किराना ले जोड़व',
      whatsappBtn: 'WhatsApp म शेयर करव',
      instagramBtn: 'Instagram Bio / DM लिंक',
      shareSheetBtn: 'दूसर ऐप म भेजव',
      copyBtn: 'लिंक कॉपी करव',
      copied: 'लिंक कॉपी होगे! ✅',
      referralNotice: '🎁 रेफरल बोनस: संगी ला जोड़े बर दूनों ला +15 दिन प्रो ट्रायल मुफ़्त!',
      messageTemplate: 'नमस्ते! मैं अपन दुकान म "ग्रामीण किराना" ऐप चलावत हौं। ये 100% बिना नेट के चलथे — तुरते बिलिंग, उधारी बही-खाता, बारकोड स्कैनर अउ ब्लूटूथ प्रिंटर सब मुफ़्त हे। तहुँ अपन दुकान बर आज़माव:\n\n'
    },
    faqs: {
      title: 'अक्सर पूछे जाने वाले सवाल (FAQs)',
      subtitle: 'गाँव के दुकानदार मन के सबले बड़े सवाल के सीधा जवाब',
      badge: 'मदद अउ समाधान',
      startShopAction: '👉 अभी अपन दुकान शुरू करव (15 सेकंड म) ➔',
      items: [
        {
          q: 'का ये ऐप सच म बिना इंटरनेट (100% ऑफ़लाइन) चलथे?',
          a: 'हव! ग्रामीण किराना ला गाँव के कमजोर नेटवर्क अउ बिजली कटौती ला देख के बनाए गे हे। बिलिंग, उधारी बही-खाता, बारकोड स्कैन, हाट-बाजार मोड अउ गल्ला हिसाब बिना नेट के सुपरफ़ास्ट चलथे। नेटवर्क आए म डाटा अपने-आप क्लाउड म सुरक्षित हो जाथे।'
        },
        {
          q: 'का "गाँव स्टार्टर" प्लान सच म जिनगी भर मुफ़्त (Free Forever) हे?',
          a: 'बिल्कुल! गाँव स्टार्टर प्लान ₹0 जिनगी भर मुफ़्त हे। एमा ऑफ़लाइन बिलिंग, असीमित उधारी खाता, बारकोड स्कैनर, हाट मोड अउ ब्लूटूथ प्रिंटिंग बर कभू कोनो पइसा नइ लागे।'
        },
        {
          q: 'यदि मोर मोबाइल फूट जाय, चोरी हो जाय, त का दुकान के डाटा बांचही?',
          a: 'हव, 100% बांचही! ऐप म "डाटा बैकअप" (JSON फ़ाइल) डाउनलोड करे के सुविधा हे। एकर अलावा प्रो प्लान म क्लाउड ऑटो-बैकअप मिलथे, जेकर से नवा फोन म सिरिफ अपन मोबाइल नंबर अउ गुप्त पिन डारतेच पूरा दुकान 1 सेकंड म वापस आ जाथे।'
        },
        {
          q: 'का मोला कोनो महँगा कंप्यूटर, बारकोड गन या प्रिंटर बिसाए ला परही?',
          a: 'नइ! तँय अपन कोनो भी साधारण 4G एंड्रॉयड स्मार्टफोन ले पूरा काम कर सकथस। बारकोड स्कैनिंग मोबाइल के कैमरा ले होथे। यदि ग्राहक ला पर्ची देना हे, त 1200-1500 रुपिया के कोनो भी ब्लूटूथ प्रिंटर जोड़ सकथस।'
        },
        {
          q: 'का ग्राहक ला ओकर WhatsApp म उधारी अउ बिल के रसीद मिलही?',
          a: 'हव! हर बिल बने म, उधारी ले जाए म या जमा मिले म 1 टैप म ग्राहक के WhatsApp म सुंदर रसीद भेज सकथस। संग म ग्राहक ला डिजिटल पासबुक लिंक मिलथे, जेकर ले वो अपन फोन म पूरा हिसाब देख सकथे।'
        },
        {
          q: 'दुकान म मुनीम या लइका बइठथे — का वो मोर मुनाफ़ा अउ थोक भाव देख पाही?',
          a: 'बिल्कुल नइ! मुनीम बर अलग 4-अंक के गुप्त PIN बना सकथस। मुनीम सिरिफ बिल काट सकथे। दुकान के शुद्ध नफ़ा, थोक भाव, गल्ला हिसाब अउ सेटिंग्स मुनीम ले पूरी तरह लुके रहिथे।'
        },
        {
          q: 'ऐप म अपन दुकान शुरू करे म कतका समय लगही?',
          a: 'सिरिफ 15 ले 30 सेकंड! अपन मोबाइल नंबर अउ 4-अंक के गुप्त पिन बनाव। दुकान सेटअप विज़ार्ड ले गाँव म बिकने वाला 52 किराना सामान 1 क्लिक म लोड हो जाथे।'
        }
      ]
    }
  },
  en: {
    appName: 'Gramin Kirana',
    appSubtitle: '100% Offline Village Grocery POS & Udhaar Khata',
    online: 'Online',
    offline: '100% Offline Active (Data Saved)',
    tabs: {
      pos: '⚡ Quick POS',
      khata: '📒 Udhaar (Khata)',
      mandi: '🛒 Mandi Restock',
      spoilage: '⚠️ Spoilage & Expiry',
      inventory: '📦 All Stock',
      settings: '⚙️ Settings & Backup',
      cashClose: '🏦 Cash Drawer',
      haat: '🎪 Haat Bazaar',
      more: '☰ Menu'
    },
    pos: {
      searchPlaceholder: 'Search item (e.g. Rice, Oil, Kurkure, Toffee)...',
      allCategories: 'All',
      categoryNames: {
        staples: 'Grains & Flour',
        pulses: 'Pulses (Daal)',
        oils: 'Oil & Ghee',
        spices: 'Spices & Sugar',
        snacks: 'Snacks & Kids Treats',
        hygiene: 'Soaps & Care',
        dairy: 'Dairy & Drinks',
        rural_special: 'Rural Specials'
      },
      cartTitle: 'Current Bill',
      emptyCart: 'Cart is empty. Select items from the left.',
      looseSelector: 'Loose Weight:',
      looseGram: 'grams',
      looseKg: 'kg',
      customItem: 'Add Custom Item (+)',
      customItemName: 'Item Name',
      customItemPrice: 'Price (₹)',
      totalPayable: 'Total Payable:',
      paymentMode: 'Payment Mode:',
      cash: 'Cash',
      udhaar: 'Udhaar (Credit)',
      upi: 'Online (UPI)',
      selectCustomer: 'Select Customer (for credit)',
      finishBill: 'Complete Bill & Receipt',
      billSuccess: 'Bill saved successfully!',
      printShare: 'Share Bill via WhatsApp',
      clearCart: 'Clear Bill',
      editRate: 'Edit Rate',
      todayRate: "Today's Rate",
      saveToCatalog: 'Save new price to catalog',
      ratePerUnit: 'per'
    },
    khata: {
      title: 'Customer Udhaar (Credit Ledger)',
      subtitle: 'Linked with harvest & DBT scheme payment cycles',
      totalUdhaar: 'Total Village Outstanding',
      totalCustomers: 'Credit Customers',
      overdueWarning: 'Overdue Payments',
      searchCustomer: 'Search customer name or phone...',
      filterByPara: 'Filter by Village Mohalla / Para:',
      allParas: 'All Mohallas / Paras',
      newCustomerBtn: '+ New Customer',
      jamaBtn: 'Payment (+)',
      udhaarBtn: 'Credit (-)',
      balance: 'Balance Due:',
      dueDate: 'Target Repayment:',
      repaymentReason: 'Repayment Method:',
      reasons: {
        KHARIF_DHAN: '🌾 Paddy Procurement (Dhan Kharidi)',
        MONTHLY_DBT: '🏛️ Mahtari Vandan / PM-KISAN',
        WEEKLY_HAAT: '🎪 Weekly Haat-Bazaar',
        OTHER: 'Other'
      },
      whatsappReminder: 'WhatsApp Reminder',
      viewLedger: 'View Full Ledger',
      digitalPassbook: '📖 Digital Passbook',
      noHistory: 'No transaction history'
    },
    mandi: {
      title: 'Mandi / Town Restock Planner',
      subtitle: 'Calculate needed procurement budget and items before traveling',
      estimatedBudget: 'Estimated Cash Needed for Mandi',
      itemsToBuy: 'Items Low on Stock',
      autoGeneratedNotice: 'Items running below threshold have been auto-added.',
      productName: 'Product Name',
      currentStock: 'Current Stock',
      suggestedQty: 'Procure Qty',
      wholesalePrice: 'Wholesale Rate',
      totalCost: 'Total Cost',
      shareWholesaler: '📲 WhatsApp List to Town Wholesaler',
      addItemManually: '+ Add Item Manually',
      dailyRateSheet: '🌅 Daily Rate Sheet',
      dailyRateSheetSubtitle: 'Update retail prices for key commodities in 1 click every morning',
      applyAllRates: '💾 Apply All New Rates',
      shareRateBoard: '📲 Share Rate Board on WhatsApp',
      currentRate: 'Current Rate',
      todayNewRate: "Today's New Rate",
      staplesOnly: '🌾 Daily Staples Only',
      allItems: '📦 All Products'
    },
    spoilage: {
      title: 'Spoilage & Expiry Guard',
      subtitle: 'Track losses from load shedding, summer heat, pests, or expired items',
      totalLoss: 'Total Loss from Spoilage',
      logLossBtn: '+ Log New Loss',
      expiringSoon: 'Expiring Within 7 Days',
      noExpiring: 'No items nearing expiry date.',
      expiringBannerTitle: 'Product Expiry Alert',
      distributorClaimBtn: '📲 Distributor Return Claim (WhatsApp)',
      reasonLabels: {
        POWER_CUT: '⚡ Power Cut / Load Shedding (Milk/Curd/Cold Drinks)',
        HEAT_DAMAGE: '☀️ Heat / Humidity Damage',
        EXPIRED: '⌛ Expired (Distributor refused return)',
        RODENT_PEST: '🐀 Rodent / Weevil Pest Damage',
        OTHER: 'Other Reasons'
      }
    },
    voice: {
      btn: '🎤 Voice Input',
      listening: 'Listening... please speak (e.g., "Ramesh 200 Udhaar" or "Mustard Oil")',
      stopListening: 'Stop',
      recognized: 'Recognized:',
      help: '💡 Try saying: "Rice 2 kg", "Ramesh 150 Udhaar", "Suresh 500 Jama"'
    },
    backup: {
      title: 'Data Backup & Security',
      subtitle: 'Download backup files to protect your data if your device changes',
      exportBtn: '📥 Download Full Backup (JSON file)',
      importBtn: '📤 Restore Data from Backup File',
      clearNotice: 'This app runs 100% locally on this device without requiring internet.',
      archiveTitle: 'Fiscal Year Archiving & Local Storage Cleanup',
      archiveSubtitle: 'Archive older sales into cold storage to keep your app superfast',
      activeSales: 'Active Sales (POS)',
      archivedSales: 'Archived Sales',
      archivedTxns: 'Archived Khata',
      estimatedStorage: 'Estimated Local Storage',
      archiveBtn: '📦 Archive Sales Older Than 180 Days',
      exportArchiveBtn: '📥 Download Sales Archive',
      archiveKhataBtn: '📒 Archive Settled Khata (Cleared Dues)',
      exportKhataArchiveBtn: '📥 Download Khata Archive'
    },
    cloudSync: {
      syncNow: 'Cloud Sync Now',
      synced: 'Cloud Secured',
      pending: 'Sync Pending',
      ownerRole: 'Store Owner',
      cashierRole: 'Counter Cashier'
    },
    cashClose: {
      title: 'Daily Cash Drawer Close',
      subtitle: 'Evening drawer closing — cash reconciliation, expenses & WhatsApp day summary',
      physicalCash: 'Physical Cash in Drawer (₹)',
      physicalCashHint: 'Count actual notes & coins in the till',
      openingCashLabel: 'Morning Opening Cash (Float)',
      openingCashHint: 'Change kept in the drawer in the morning',
      denominationCounter: '💵 Count Notes & Coins',
      denominationClose: 'Hide Calculator',
      denominationApply: 'Fill Total to Drawer Cash',
      totalUpiSalesLabel: '📲 UPI / Online Sales',
      totalGrossSalesLabel: 'Total Day Turnover',
      reopenDayBtn: '🔓 Reopen / Amend Today\'s Close',
      reopenConfirm: 'Are you sure you want to reopen today\'s closing record to make adjustments?',
      cashSalesLabel: "Today's Cash Sales",
      jamaLabel: 'Udhaar Jama Collected Today',
      expensesLabel: 'Today\'s Expenses (Tempo, wages, tea, etc.)',
      addExpense: '+ Add Expense',
      expenseDesc: 'Expense Description',
      expenseAmt: 'Amount (₹)',
      expectedCash: 'Expected Total Cash',
      difference: 'Cash Reconciliation (Difference)',
      excess: 'Cash Surplus (Extra)',
      shortage: 'Cash Shortage (Deficit)',
      matched: 'Drawer Balanced Perfectly! ✅',
      note: 'Note / Remarks (Optional)',
      closeDayBtn: 'Close Day & Save',
      whatsappSummary: '📲 Send Day Summary via WhatsApp',
      printSummary: '🖨️ Print via Thermal Printer',
      closedAt: 'Closed at:',
      noHistory: 'No cash close recorded today',
      todayDate: "Today's Date",
      bluetoothConnect: 'Connect Bluetooth Printer',
      printFallback: 'Browser Print (58mm)',
      eveningReminder: 'Evening Cash Close is pending',
      closePendingBadge: 'Close Due'
    },
    haatMode: {
      title: 'Weekly Haat-Bazaar High-Speed Mode',
      subtitle: '2-Second Cash Sales for Market Day Rush — Extra-Large Buttons, 1-Tap Cash',
      todayCash: "Today's Haat Cash",
      todayBills: 'Total Customers',
      quickTender: 'Cash Tendered:',
      changeReturn: 'Change to Return:',
      finishBill: '⚡ 1-Tap Cash Complete (₹',
      finishBillUpi: '⚡ 1-Tap UPI Complete (₹',
      billSuccess: 'Sale Completed! Next Customer Ready ➔',
      autoPrint: 'Receipt Print (58mm)',
      clearCart: 'Cancel',
      adHocItem: '⚡ Loose Item / Produce (+₹)',
      paymentMode: 'Payment Mode:',
      cashMode: '💵 Cash',
      upiMode: '📲 UPI (QR Code)',
      lowStockBadge: '⚠️ Low Stock',
      soundOn: '🔊 Sound On',
      soundOff: '🔇 Sound Off'
    },
    subscription: {
      modalTitle: 'Gramin Kirana — Features & Plans',
      modalSubtitle: 'Transparent, village-friendly retail billing and khata solution',
      freePlanTitle: '🌾 Village Starter (Free)',
      freePlanPrice: '₹0',
      freePlanPeriod: 'Free Forever',
      freePlanDesc: 'Complete offline billing for independent village grocers. No hidden fees.',
      proPlanTitle: '🚀 Gramin Pro (Cloud & Multi-Staff)',
      proPlanPrice: '₹99',
      proPlanPeriod: 'per month (or ₹999/year)',
      proPlanDesc: 'WhatsApp blast reminders, monthly P&L report, low-stock alerts, cashier login & cloud backup.',
      activeBadge: 'Currently Active Plan',
      upgradeBtn: 'Upgrade to Pro (WhatsApp)',
      startFreeBtn: '+ Register Your Shop Free',
      allFeaturesTitle: '🎯 Powerful Village Counter Features',
      features: {
        offline: '100% Offline-First — Operates smoothly during rural power cuts & weak signals',
        pos: 'Rapid POS & Barcode Scanner — Camera scanner and 1-tap fractional loose quantities',
        khata: 'Bahi-Khata Ledger — Linked to crop harvests & DBT schemes with 1-tap WhatsApp reminders',
        haat: 'Weekly Haat-Bazaar Mode — High-velocity 2-second cash checkout for rush market days',
        thermal: 'Bluetooth Thermal Printing — 58mm POS receipts and customer ledger statement slips',
        galla: 'Daily Cash Closing — Evening cash till reconciliation, daily shop expenses & WhatsApp report',
        cloud: 'Cloud Backup (Pro) — Full disaster recovery if device is damaged or lost',
        staff: 'Staff/Cashier Accounts (Pro) — Safeguards wholesale supplier rates and profit margins',
        whatsappBlast: '📲 WhatsApp Bulk Reminder (Pro) — 1-tap reminder to all overdue Khata customers',
        plReport: '📊 Monthly P&L Report (Pro) — Revenue, cost, spoilage & net profit PDF',
        lowStock: '🔔 Low Stock Alert (Pro) — Morning alert for all items below reorder level',
        munimPin: '👥 Munim/Staff PIN Login (Pro) — Restrict reports & settings from counter staff'
      },
      currentPlanLabel: 'Active Shop Plan:',
      currentPlanFree: '🌾 Village Starter (Free)',
      currentPlanPro: '👑 Gramin Pro'
    },
    learnBtn: '❓ Learn',
    tour: {
      modalTitle: 'Gramin Kirana — Learn in 1 Minute',
      modalSubtitle: 'Simple illustrated guide for shop owners & cashiers',
      slides: [
        {
          title: '1. Instant Billing (1-Tap POS)',
          icon: '🧾',
          desc: 'Tap any product name or photo to instantly add it to the cart. Choose Cash, Udhaar, or UPI QR and hand over the receipt or share on WhatsApp in 1 second.',
          badge: 'Fast & Easy'
        },
        {
          title: '2. Customer Khata Ledger',
          icon: '👥',
          desc: 'Pick village customers by Para/Mohalla. Record harvest or DBT repayment dates. Visual red warnings highlight credit limit breaches with 1-tap WhatsApp reminders.',
          badge: 'Udhaar Safety'
        },
        {
          title: '3. Loose Weighing & Live Rates',
          icon: '⚖️',
          desc: 'Sell loose sugar, flour, and oil in Paav (250g), half kg (500g), or ₹10-₹20 coins. Revise daily mandi rates in just 1 tap every morning.',
          badge: 'Paav & Half Kg'
        },
        {
          title: '4. Evening Cash Till Close',
          icon: '🔒',
          desc: 'At shop closing time, count 500, 200, 100, 50, 20, 10 notes into the cash drawer. Reconcile total day sales and send summary receipts via WhatsApp.',
          badge: 'Cash Integrity'
        }
      ],
      startPracticeBtn: '🚀 Try 1-Minute Practice Bill',
      skipBtn: '✕ Learn Later',
      prevBtn: 'Back',
      nextBtn: 'Next',
      practiceBar: {
        step1: '👆 Step 1: Tap any item below (e.g. Sugar or Oil) to add to cart',
        step2: '👆 Step 2: Choose Cash/Udhaar and tap "Finish Bill" below',
        exitTour: '✕ Exit Practice'
      },
      celebration: {
        title: '🎉 Great Job! Your First Bill is Ready!',
        subtitle: 'You have successfully learned how to bill on Gramin Kirana.',
        note: '💡 Note: This was a practice bill for learning. Real inventory and ledger accounts were not affected.',
        startRealBtn: '✅ Start Real Billing Now',
        retryBtn: '🔄 Practice Again'
      },
      welcomePrompt: {
        title: 'Welcome! Would you like to learn how to make your first bill in 1 minute?',
        startBtn: '🚀 Yes, Try Practice Bill',
        dismissBtn: 'Later'
      }
    },
    share: {
      title: 'Share with Fellow Shopkeepers',
      subtitle: 'Introduce local village merchants to digital billing and ledgers',
      whatsappBtn: 'Share on WhatsApp',
      instagramBtn: 'Instagram Bio / DM Link',
      shareSheetBtn: 'Share via Other Apps',
      copyBtn: 'Copy Link',
      copied: 'Link Copied! ✅',
      referralNotice: '🎁 Referral Bonus: Both you and your friend get +15 Days of Pro Trial Free!',
      messageTemplate: 'Hello! I am using the "Gramin Kirana" app for my village store. It runs 100% offline — quick POS billing, Udhaar khata, barcode scanning, and bluetooth receipts are all free. Try it for your store:\n\n'
    },
    faqs: {
      title: 'Frequently Asked Questions (FAQs)',
      subtitle: 'Clear answers to common questions asked by village store owners',
      badge: 'Help & Answers',
      startShopAction: '👉 Start Your Store Now (in 15 seconds) ➔',
      items: [
        {
          q: 'Does this app really work 100% offline without the internet?',
          a: 'Yes! Gramin Kirana is engineered specifically for rural areas with weak networks or power outages. POS billing, Udhaar ledger, barcode scanning, weekly Haat mode, and evening cash closing work superfast completely offline. Data automatically syncs when connectivity is available.'
        },
        {
          q: 'Is the "Village Starter" plan truly Free Forever?',
          a: 'Absolutely! The Village Starter plan is ₹0 lifetime free. Offline billing, unlimited Udhaar Khata, camera barcode scanning, weekly Haat mode, and 58mm Bluetooth receipt printing carry zero charges forever.'
        },
        {
          q: 'If my phone is lost, damaged, or upgraded, is my store data safe?',
          a: 'Yes, 100% safe! You can download a complete offline JSON backup at any time. Additionally, the Pro plan offers secure cloud auto-sync, so entering your mobile number and secret PIN on any new phone restores your store, customer debts, and inventory in seconds.'
        },
        {
          q: 'Do I need to buy an expensive computer, barcode gun, or printer?',
          a: 'Not at all! You can run everything from any regular 4G Android smartphone. Barcode scanning uses your phone camera. If you wish to provide paper receipts, any affordable ₹1200-₹1500 wireless Bluetooth thermal printer can be paired instantly.'
        },
        {
          q: 'Will customers receive digital receipts and Khata passbooks on WhatsApp?',
          a: 'Yes! Upon generating a bill, extending credit, or receiving a repayment, you can send an itemized receipt to the customer via WhatsApp in 1 tap. Customers also receive a secure passbook link to review their complete balance history on their own phone.'
        },
        {
          q: 'If staff or a cashier works the counter, can they see my profit margins and wholesale purchase rates?',
          a: 'No! You can configure a 4-digit Munim PIN. Staff can only bill customers and record credit. Wholesale purchase rates, net profit reports, evening cash drawer closing, and store settings remain strictly locked and private.'
        },
        {
          q: 'How long does it take to set up and start using the app?',
          a: 'Only 15 to 30 seconds! Enter your mobile number and choose a 4-digit PIN. The Store Setup Wizard can pre-load 52 popular village grocery products (sugar, edible oils, pulses, spices, soap, biscuits) in just 1 tap.'
        }
      ]
    }
  }
};
